{"nick":"apapirovski","reason":"Remote host closed the connection","date":"2018-02-26T00:06:22.733Z","type":"quit"}
{"nick":"node-gh","date":"2018-02-26T00:10:22.128Z","type":"join"}
{"nick":"node-gh","date":"2018-02-26T00:10:22.201Z","type":"part"}
{"nick":"node-gh","date":"2018-02-26T00:13:21.965Z","type":"join"}
{"nick":"node-gh","date":"2018-02-26T00:13:22.033Z","type":"part"}
{"nick":"node-gh","date":"2018-02-26T00:20:01.906Z","type":"join"}
{"nick":"node-gh","date":"2018-02-26T00:20:01.907Z","type":"part"}
{"nick":"node-gh","date":"2018-02-26T01:52:51.150Z","type":"join"}
{"nick":"node-gh","date":"2018-02-26T01:52:51.219Z","type":"part"}
{"nick":"BridgeAR","reason":"Ping timeout: 245 seconds","date":"2018-02-26T02:20:12.062Z","type":"quit"}
{"nick":"node-gh","date":"2018-02-26T03:22:12.244Z","type":"join"}
{"nick":"node-gh","date":"2018-02-26T03:22:12.281Z","type":"part"}
{"nick":"node-gh","date":"2018-02-26T05:01:13.229Z","type":"join"}
{"nick":"node-gh","date":"2018-02-26T05:01:13.334Z","type":"part"}
{"nick":"node-gh","date":"2018-02-26T05:39:42.165Z","type":"join"}
{"nick":"node-gh","date":"2018-02-26T05:39:42.235Z","type":"part"}
{"nick":"node-gh","date":"2018-02-26T05:40:31.365Z","type":"join"}
{"nick":"node-gh","date":"2018-02-26T05:40:31.470Z","type":"part"}
{"nick":"rvagg","message":"ok, Pi1's are all sorted out, there's been a run of bad executions over the past 24 hours due to missing `git` on some hosts .. my fault, botched upgrade with ansible not finishing on some of them","date":"2018-02-26T05:41:33.005Z","type":"message"}
{"nick":"seishun","date":"2018-02-26T07:34:25.295Z","type":"join"}
