{"nick":"gibson042","reason":"Quit: Leaving.","date":"2018-11-24T01:10:31.961Z","type":"quit"}
{"nick":"devsnek","message":"is HostPromiseRejectionTracker supposed to be used in test262 to detect the failure of async tests?","date":"2018-11-24T04:41:43.789Z","type":"message"}
{"nick":"devsnek","message":"it isn't mentioned in interpreting.md but it doesn't seem like there is any other way.","date":"2018-11-24T04:42:35.112Z","type":"message"}
{"nick":"jmdyck","reason":"Remote host closed the connection","date":"2018-11-24T05:45:50.535Z","type":"quit"}
{"nick":"Bakkot","message":"devsnek: I just use a timeout, as INTERPRETING.md suggests: \"The implementation is free to select an appropriate length of time to wait before considering the test \"timed out\" and failing.\"","date":"2018-11-24T05:48:31.444Z","type":"message"}
