{"nick":"zsoc","reason":"Ping timeout: 268 seconds","date":"2018-12-23T03:15:32.689Z","type":"quit"}
{"nick":"antsmartian","date":"2018-12-23T04:46:00.844Z","type":"join"}
{"nick":"antsmart_","date":"2018-12-23T04:59:21.411Z","type":"join"}
{"nick":"antsmartian","reason":"Ping timeout: 250 seconds","date":"2018-12-23T05:01:23.677Z","type":"quit"}
{"nick":"antsmart_","reason":"Remote host closed the connection","date":"2018-12-23T05:16:00.556Z","type":"quit"}
{"nick":"antsmartian","date":"2018-12-23T05:16:54.886Z","type":"join"}
{"nick":"antsmartian","reason":"Ping timeout: 250 seconds","date":"2018-12-23T05:21:19.719Z","type":"quit"}
{"nick":"lpin","date":"2018-12-23T06:04:46.157Z","type":"join"}
{"nick":"d10n-work","reason":"Ping timeout: 252 seconds","date":"2018-12-23T06:47:57.706Z","type":"quit"}
{"nick":"d10n-work","date":"2018-12-23T06:50:46.724Z","type":"join"}
{"nick":"xkapastel","reason":"Quit: Connection closed for inactivity","date":"2018-12-23T07:10:21.285Z","type":"quit"}
{"nick":"seishun","date":"2018-12-23T09:35:03.727Z","type":"join"}
{"nick":"zeds","date":"2018-12-23T10:01:38.537Z","type":"join"}
{"nick":"zeds","date":"2018-12-23T10:01:46.861Z","type":"part"}
{"nick":"seishun","reason":"Ping timeout: 250 seconds","date":"2018-12-23T10:26:20.913Z","type":"quit"}
{"nick":"seishun","date":"2018-12-23T10:45:07.350Z","type":"join"}
{"nick":"seishun","reason":"Ping timeout: 240 seconds","date":"2018-12-23T10:50:07.317Z","type":"quit"}
{"nick":"seishun","date":"2018-12-23T11:09:08.493Z","type":"join"}
{"nick":"antsmartian","date":"2018-12-23T11:17:42.874Z","type":"join"}
{"nick":"AtumT","date":"2018-12-23T11:42:31.547Z","type":"join"}
{"nick":"antsmartian","reason":"Ping timeout: 250 seconds","date":"2018-12-23T11:52:11.806Z","type":"quit"}
{"nick":"seishun","reason":"Ping timeout: 246 seconds","date":"2018-12-23T12:23:46.258Z","type":"quit"}
{"nick":"antsmartian","date":"2018-12-23T12:31:26.611Z","type":"join"}
{"nick":"seishun","date":"2018-12-23T12:55:00.201Z","type":"join"}
{"nick":"antsmartian","reason":"Remote host closed the connection","date":"2018-12-23T13:06:16.167Z","type":"quit"}
{"nick":"seishun","reason":"Ping timeout: 268 seconds","date":"2018-12-23T13:27:53.849Z","type":"quit"}
{"nick":"seishun","date":"2018-12-23T13:36:53.951Z","type":"join"}
{"nick":"lpin","reason":"Quit: Textual IRC Client: www.textualapp.com","date":"2018-12-23T13:40:37.221Z","type":"quit"}
{"nick":"bellare","date":"2018-12-23T17:06:06.847Z","type":"join"}
{"nick":"lpin","date":"2018-12-23T17:25:54.930Z","type":"join"}
{"nick":"xkapastel","date":"2018-12-23T17:29:20.017Z","type":"join"}
{"nick":"early`","reason":"Ping timeout: 268 seconds","date":"2018-12-23T17:36:24.774Z","type":"quit"}
{"nick":"lpin","reason":"Quit: Textual IRC Client: www.textualapp.com","date":"2018-12-23T18:47:08.299Z","type":"quit"}
{"nick":"early","date":"2018-12-23T18:50:03.320Z","type":"join"}
{"nick":"zeds","date":"2018-12-23T20:32:14.668Z","type":"join"}
{"nick":"zeds","date":"2018-12-23T20:34:06.694Z","type":"part"}
{"nick":"bellare","reason":"Quit: Connection closed for inactivity","date":"2018-12-23T20:55:45.666Z","type":"quit"}
{"nick":"joyee","message":"Fun fact: you can fail `test/async-hooks/test-timers.setInterval.js` if you add a name to the `process._fatalException` function before writing it to the process object","date":"2018-12-23T22:49:13.699Z","type":"message"}
{"nick":"devsnek","message":"joyee: sgtm","date":"2018-12-23T23:03:19.026Z","type":"message"}
{"nick":"joyee","message":"devsnek: why?","date":"2018-12-23T23:03:39.030Z","type":"message"}
{"nick":"devsnek","message":"lol i was kidding","date":"2018-12-23T23:03:48.609Z","type":"message"}
{"nick":"joyee","message":"lol","date":"2018-12-23T23:03:54.780Z","type":"message"}
{"nick":"devsnek","message":"is that because of matching error stack output","date":"2018-12-23T23:04:05.327Z","type":"message"}
{"nick":"joyee","message":"I don't think so, the test is fails because there is a before hook missing","date":"2018-12-23T23:04:27.128Z","type":"message"}
{"nick":"joyee","message":"Something is probably wrong with the way node::FatalException call into JS, there is no async context there","date":"2018-12-23T23:05:17.277Z","type":"message"}
{"nick":"devsnek","message":"oh i had that issue when i was making queueMicrotask","date":"2018-12-23T23:06:17.575Z","type":"message"}
{"nick":"joyee","message":"hmm, maybe the function should do a runInAsyncScope","date":"2018-12-23T23:07:26.953Z","type":"message"}
{"nick":"joyee","message":"But I am not even sure if that's safe","date":"2018-12-23T23:07:33.770Z","type":"message"}
{"nick":"joyee","message":"Considering it's cleaning up the stack","date":"2018-12-23T23:08:15.101Z","type":"message"}
{"nick":"joyee","message":"(But that still does not explain why the test fails if you name the function)","date":"2018-12-23T23:13:12.606Z","type":"message"}
{"nick":"AtumT","reason":"Quit: AtumT","date":"2018-12-23T23:35:53.702Z","type":"quit"}
{"nick":"seishun","reason":"Ping timeout: 268 seconds","date":"2018-12-23T23:37:46.692Z","type":"quit"}
