{"nick":"TimothyGu","message":"ye","date":"2018-03-23T00:01:22.741Z","type":"message"}
{"nick":"TimothyGu","message":"devsnek: ping on https://github.com/nodejs/node/issues/19503","date":"2018-03-23T00:01:58.526Z","type":"message"}
{"nick":"devsnek","message":"it was working locally, i'm weirded out","date":"2018-03-23T00:02:22.075Z","type":"message"}
{"nick":"TimothyGu","message":"Only got notifications down to 843 and I'm already tired :(","date":"2018-03-23T00:05:39.671Z","type":"message"}
{"nick":"devsnek","message":"poor tim","date":"2018-03-23T00:06:28.514Z","type":"message"}
{"nick":"ahmadassaf","reason":"Quit: My Mac has gone to sleep. ZZZzzzâ€¦","date":"2018-03-23T00:12:54.965Z","type":"quit"}
{"nick":"AtumT","reason":"Remote host closed the connection","date":"2018-03-23T00:48:39.806Z","type":"quit"}
{"nick":"marthinal","date":"2018-03-23T01:12:12.210Z","type":"join"}
{"nick":"marthinal","reason":"Ping timeout: 276 seconds","date":"2018-03-23T01:17:20.118Z","type":"quit"}
{"nick":"gabrielschulhof","date":"2018-03-23T02:44:35.817Z","type":"join"}
{"nick":"gabrielschulhof","message":"Hey, all! Does a CallbackScope take care to propagate exceptions back into JS such that they appear with a reasonable stack?","date":"2018-03-23T02:45:11.996Z","type":"message"}
{"nick":"gabrielschulhof","message":"The reason I ask is that at https://github.com/nodejs/node/blob/master/src/node_api.cc#L3365 we through a fatal exception if the async work complete callback throws an exception. If the CallbackScope properly handles the exception, we should just re-throw it, and not convert it to a fatal.","date":"2018-03-23T02:46:42.803Z","type":"message"}
{"nick":"gabrielschulhof","message":"s/through/throw/","date":"2018-03-23T02:46:51.472Z","type":"message"}
{"nick":"devsnek","message":"BridgeAR: did you ever get your patch for console.table finished up?","date":"2018-03-23T02:51:05.485Z","type":"message"}
{"nick":"TimothyGu","message":"devsnek: you do realize that he's not here right :D","date":"2018-03-23T02:58:01.039Z","type":"message"}
{"nick":"howdoi","date":"2018-03-23T03:31:48.598Z","type":"join"}
{"nick":"marthinal","date":"2018-03-23T04:12:26.718Z","type":"join"}
{"nick":"early","reason":"Quit: Leaving","date":"2018-03-23T04:16:39.651Z","type":"quit"}
{"nick":"marthinal","reason":"Ping timeout: 268 seconds","date":"2018-03-23T04:17:02.609Z","type":"quit"}
{"nick":"early","date":"2018-03-23T04:19:45.104Z","type":"join"}
{"nick":"gabrielschulhof","reason":"Ping timeout: 264 seconds","date":"2018-03-23T04:21:22.058Z","type":"quit"}
{"nick":"doodadjs_","date":"2018-03-23T04:46:00.462Z","type":"join"}
{"nick":"doodadjs","reason":"Ping timeout: 264 seconds","date":"2018-03-23T04:47:09.234Z","type":"quit"}
{"nick":"doodadjs_","reason":"Ping timeout: 256 seconds","date":"2018-03-23T04:52:27.458Z","type":"quit"}
{"nick":"doodadjs","date":"2018-03-23T04:55:26.354Z","type":"join"}
{"nick":"lpin","date":"2018-03-23T05:51:50.810Z","type":"join"}
{"nick":"marthinal","date":"2018-03-23T05:57:46.406Z","type":"join"}
{"nick":"marthinal","reason":"Remote host closed the connection","date":"2018-03-23T06:05:47.640Z","type":"quit"}
{"nick":"chalker_","date":"2018-03-23T06:11:11.050Z","type":"join"}
{"nick":"marthinal","date":"2018-03-23T06:50:44.552Z","type":"join"}
{"nick":"chalker_","reason":"Ping timeout: 246 seconds","date":"2018-03-23T07:14:33.987Z","type":"quit"}
{"nick":"chalker_","date":"2018-03-23T07:20:27.078Z","type":"join"}
{"nick":"not-an-aardvark","reason":"Quit: Connection closed for inactivity","date":"2018-03-23T07:37:49.253Z","type":"quit"}
{"nick":"al-damiri","reason":"Quit: Connection closed for inactivity","date":"2018-03-23T07:52:15.157Z","type":"quit"}
