{"nick":"marthinal","date":"2018-10-20T00:07:41.578Z","type":"join"}
{"nick":"marthinal","reason":"Ping timeout: 252 seconds","date":"2018-10-20T00:12:06.387Z","type":"quit"}
{"nick":"nix","reason":"Ping timeout: 252 seconds","date":"2018-10-20T00:26:57.456Z","type":"quit"}
{"nick":"AtumT","reason":"Quit: AtumT","date":"2018-10-20T00:30:04.846Z","type":"quit"}
{"nick":"nix","date":"2018-10-20T00:48:46.377Z","type":"join"}
{"nick":"devsnek","message":"how are errors from nextTick caught in repl","date":"2018-10-20T01:02:18.734Z","type":"message"}
{"nick":"addaleax","message":"devsnek: `domain`s?","date":"2018-10-20T01:05:29.077Z","type":"message"}
{"nick":"addaleax","message":"refack: is there a reason you assign PRs like e.g. https://github.com/nodejs/node/pull/23354 to yourself?","date":"2018-10-20T01:05:45.563Z","type":"message"}
{"nick":"devsnek","message":"addaleax: does the default _fatalException not handle domains?","date":"2018-10-20T01:06:04.598Z","type":"message"}
{"nick":"addaleax","message":"devsnek: it calls the domain exception capture handler first, and that is the one that tells the REPL about the exception","date":"2018-10-20T01:06:36.976Z","type":"message"}
{"nick":"devsnek","message":"i don't see any domain specific stuff in nextTick","date":"2018-10-20T01:06:41.024Z","type":"message"}
{"nick":"refack","message":"Just so it's easier for me to track them","date":"2018-10-20T01:06:43.100Z","type":"message"}
{"nick":"devsnek","message":"but when i trigger the fatal exception thingy with microtasks it just kills the process","date":"2018-10-20T01:06:55.868Z","type":"message"}
{"nick":"devsnek","message":"in the repl","date":"2018-10-20T01:06:57.426Z","type":"message"}
{"nick":"refack","message":"It's the best way I found to get specific notification from GitHub","date":"2018-10-20T01:07:39.671Z","type":"message"}
{"nick":"devsnek","message":"just click \"subscribe\"","date":"2018-10-20T01:07:48.032Z","type":"message"}
{"nick":"devsnek","message":"or whatever it is","date":"2018-10-20T01:07:51.184Z","type":"message"}
{"nick":"devsnek","message":"yeah subscribe","date":"2018-10-20T01:08:01.429Z","type":"message"}
{"nick":"addaleax","message":"refack: itâ€™s a bit confusing since it might keep people from landing PRs, if you donâ€™t make that explicit","date":"2018-10-20T01:08:06.378Z","type":"message"}
{"nick":"devsnek","message":"refack: https://gc.gy/7702732.png","date":"2018-10-20T01:08:19.419Z","type":"message"}
{"nick":"addaleax","message":"devsnek: so â€¦ Iâ€™m not sure, are you talking about queueMicrotask?","date":"2018-10-20T01:08:29.934Z","type":"message"}
{"nick":"devsnek","message":"yes","date":"2018-10-20T01:08:33.999Z","type":"message"}
{"nick":"addaleax","message":"that doesnâ€™t seem to work with domains so far, yes","date":"2018-10-20T01:08:36.997Z","type":"message"}
{"nick":"devsnek","message":"v8 currently doesn't track errors in it at all","date":"2018-10-20T01:08:40.702Z","type":"message"}
{"nick":"devsnek","message":"which is why its failing silently","date":"2018-10-20T01:08:45.304Z","type":"message"}
{"nick":"refack","message":"That one needs an other TSC vote. If it author ready, either land or unassign","date":"2018-10-20T01:08:58.027Z","type":"message"}
{"nick":"devsnek","message":"so i bound our FatalException method to be called manually","date":"2018-10-20T01:09:02.296Z","type":"message"}
{"nick":"devsnek","message":"but its not taking the same path as nextTick somehow","date":"2018-10-20T01:09:09.108Z","type":"message"}
{"nick":"addaleax","message":"refack: why does it need a TSC vote?","date":"2018-10-20T01:09:29.121Z","type":"message"}
{"nick":"addaleax","message":"we do seem to have consensus there?","date":"2018-10-20T01:09:34.403Z","type":"message"}
{"nick":"refack","message":"I'm subscribed to too many, and GitHub GUI does have a \"subscribed to\" filter","date":"2018-10-20T01:09:43.930Z","type":"message"}
{"nick":"refack","message":"Semver major","date":"2018-10-20T01:09:51.412Z","type":"message"}
{"nick":"devsnek","message":"i don't understand where domains handle fatal exceptions","date":"2018-10-20T01:09:56.829Z","type":"message"}
{"nick":"addaleax","message":"refack: that doesnâ€™t mean it needs a vote â€“ it needs 2 TSC approvals, which it has","date":"2018-10-20T01:10:14.117Z","type":"message"}
{"nick":"addaleax","message":"refack: itâ€™s only waiting for CI now, and thatâ€™s what author-ready is for","date":"2018-10-20T01:10:28.710Z","type":"message"}
{"nick":"refack","message":"Yeah I mean approval","date":"2018-10-20T01:10:52.331Z","type":"message"}
{"nick":"devsnek","message":"ok i figured this path out","date":"2018-10-20T01:12:24.332Z","type":"message"}
{"nick":"addaleax","message":"devsnek: so â€¦ https://github.com/nodejs/node/blob/master/lib/internal/bootstrap/node.js#L618-L619 is the part of _fatalException that handles this","date":"2018-10-20T01:12:43.802Z","type":"message"}
{"nick":"devsnek","message":"but the captureFn is called in _fatalException","date":"2018-10-20T01:12:46.005Z","type":"message"}
{"nick":"devsnek","message":"yeah","date":"2018-10-20T01:12:47.096Z","type":"message"}
{"nick":"devsnek","message":"if you don't mind looking... https://gist.github.com/devsnek/6253a6ea8f334a066abc6721c320c85d","date":"2018-10-20T01:13:11.504Z","type":"message"}
{"nick":"devsnek","message":"calling my triggerFatalException method is skipping the captureFn somehow","date":"2018-10-20T01:13:33.479Z","type":"message"}
{"nick":"addaleax","message":"devsnek: because we donâ€™t have async_hooks support for queueMicrotask at this point either, as far as I can tell?","date":"2018-10-20T01:14:51.493Z","type":"message"}
{"nick":"devsnek","message":"i don't understand","date":"2018-10-20T01:15:01.810Z","type":"message"}
{"nick":"refack","message":"Unassigned myself. But IMHO explicitly declaring \"stewardship\" gives the author the feeling they are not ignored. I thought you'd be supportive of taking responsibility, not being critical ðŸ¤·","date":"2018-10-20T01:15:04.360Z","type":"message"}
{"nick":"devsnek","message":"i've taken assignment to mean that you would be performing whatever changes etc yourslef","date":"2018-10-20T01:15:27.628Z","type":"message"}
{"nick":"refack","message":"Like the bit we added to the guide \"if in doubt ask\"","date":"2018-10-20T01:15:29.997Z","type":"message"}
{"nick":"devsnek","message":"yourself*","date":"2018-10-20T01:15:31.048Z","type":"message"}
{"nick":"devsnek","message":"not that you're advising them","date":"2018-10-20T01:15:36.796Z","type":"message"}
{"nick":"devsnek","message":"i think you need to be explicit about that","date":"2018-10-20T01:15:40.992Z","type":"message"}
{"nick":"addaleax","message":"refack: yes, thatâ€™s why iâ€™m asking? iâ€™m not critical of taking responsiblity","date":"2018-10-20T01:15:46.523Z","type":"message"}
{"nick":"addaleax","message":"^^^ what devsnek says","date":"2018-10-20T01:15:49.521Z","type":"message"}
{"nick":"refack","message":"Ok, fair","date":"2018-10-20T01:15:57.464Z","type":"message"}
{"nick":"addaleax","message":"devsnek: domains track async context through async_hooks, but right now thereâ€™s nothing in place that tracks async context for queueMicrotask() afaict?","date":"2018-10-20T01:16:18.951Z","type":"message"}
{"nick":"devsnek","message":"i have the AsyncResource thing","date":"2018-10-20T01:16:31.815Z","type":"message"}
{"nick":"devsnek","message":"are you saying the domain doesn't think that error belongs to it?","date":"2018-10-20T01:16:45.764Z","type":"message"}
{"nick":"refack","message":"I don't do that often but since I was the main critique for that PR I wanted to make sure I don't lose track of it, and that the author knows that.","date":"2018-10-20T01:17:15.096Z","type":"message"}
{"nick":"refack","message":"If needed in the future I'll be explicit","date":"2018-10-20T01:17:32.566Z","type":"message"}
{"nick":"addaleax","message":"devsnek: oh, I see â€¦ the issue is that you call triggerFatalException() outside of the runInAsyncScope() cb, I assume","date":"2018-10-20T01:18:31.240Z","type":"message"}
{"nick":"devsnek","message":"oh boy if that fixes this","date":"2018-10-20T01:18:45.723Z","type":"message"}
{"nick":"devsnek","message":"shame to have two try/catches though","date":"2018-10-20T01:18:53.917Z","type":"message"}
{"nick":"devsnek","message":"oh and the semantics of calling emitDestroy","date":"2018-10-20T01:19:27.862Z","type":"message"}
{"nick":"devsnek","message":"should that be unconditionally called or only if there's no error","date":"2018-10-20T01:19:39.211Z","type":"message"}
{"nick":"addaleax","message":"devsnek: idk, it might be worth thinking about implementing this in terms of Promises? that would take care of all the async context trackingâ€¦","date":"2018-10-20T01:19:48.635Z","type":"message"}
{"nick":"devsnek","message":"like using Promise.resolve().then() instead of EnqueueMicrotask?","date":"2018-10-20T01:20:09.893Z","type":"message"}
{"nick":"addaleax","message":"devsnek: so â€¦ Iâ€™d go with unconditionally, but the timing for it might be icky (thereâ€™s a longer comment on a similar problem in internal/process/next_tick.js)","date":"2018-10-20T01:20:33.674Z","type":"message"}
{"nick":"addaleax","message":"devsnek: yeah, thatâ€¦","date":"2018-10-20T01:20:40.839Z","type":"message"}
{"nick":"devsnek","message":"yeah i saw the thing in nextTick","date":"2018-10-20T01:20:47.941Z","type":"message"}
{"nick":"devsnek","message":"but since i'm inside the microtask queue i don't think i can do the same thing","date":"2018-10-20T01:20:59.157Z","type":"message"}
{"nick":"devsnek","message":"perhaps putting the destroy in finally","date":"2018-10-20T01:21:38.064Z","type":"message"}
{"nick":"devsnek","message":"addaleax: calling the fatal handler inside worked, thanks","date":"2018-10-20T01:23:15.671Z","type":"message"}
{"nick":"antsmartian","date":"2018-10-20T02:17:14.041Z","type":"join"}
{"nick":"antsmartian","reason":"Remote host closed the connection","date":"2018-10-20T02:17:16.277Z","type":"quit"}
{"nick":"antsmartian","date":"2018-10-20T02:17:31.817Z","type":"join"}
{"nick":"al-damiri","reason":"Quit: Connection closed for inactivity","date":"2018-10-20T02:27:22.873Z","type":"quit"}
{"nick":"antsmartian","reason":"Remote host closed the connection","date":"2018-10-20T02:28:46.411Z","type":"quit"}
{"nick":"zeds1","date":"2018-10-20T02:37:19.463Z","type":"join"}
{"nick":"zeds1","date":"2018-10-20T02:42:07.134Z","type":"part"}
{"nick":"doodadjs","reason":"Ping timeout: 246 seconds","date":"2018-10-20T03:03:31.245Z","type":"quit"}
{"nick":"joyee","message":"I am still puzzled why we have queueMicrotask...that seems to be a request from Angular and so far only Chrome has implemented it","date":"2018-10-20T03:39:47.124Z","type":"message"}
{"nick":"antsmartian","date":"2018-10-20T03:56:46.713Z","type":"join"}
{"nick":"marthinal","date":"2018-10-20T04:08:07.674Z","type":"join"}
{"nick":"marthinal","reason":"Ping timeout: 268 seconds","date":"2018-10-20T04:12:49.362Z","type":"quit"}
{"nick":"antsmartian","reason":"Ping timeout: 244 seconds","date":"2018-10-20T04:34:17.529Z","type":"quit"}
{"nick":"nix","reason":"Ping timeout: 252 seconds","date":"2018-10-20T04:38:51.372Z","type":"quit"}
{"nick":"devsnek","message":"joyee: actually only safari has it so far","date":"2018-10-20T04:52:33.491Z","type":"message"}
{"nick":"antsmartian","date":"2018-10-20T05:00:08.445Z","type":"join"}
{"nick":"antsmartian","reason":"Remote host closed the connection","date":"2018-10-20T05:01:33.582Z","type":"quit"}
{"nick":"antsmartian","date":"2018-10-20T05:16:21.543Z","type":"join"}
{"nick":"lpin","date":"2018-10-20T05:22:28.711Z","type":"join"}
{"nick":"ljharb","message":"seems pretty early to have it in node","date":"2018-10-20T05:23:07.260Z","type":"message"}
{"nick":"johannh","reason":"Ping timeout: 276 seconds","date":"2018-10-20T05:36:14.882Z","type":"quit"}
{"nick":"johannh","date":"2018-10-20T05:39:34.335Z","type":"join"}
{"nick":"johannh","reason":"Ping timeout: 252 seconds","date":"2018-10-20T05:43:57.593Z","type":"quit"}
{"nick":"johannh","date":"2018-10-20T05:50:33.741Z","type":"join"}
{"nick":"antsmartian","reason":"Remote host closed the connection","date":"2018-10-20T06:29:31.509Z","type":"quit"}
{"nick":"antsmartian","date":"2018-10-20T07:17:38.713Z","type":"join"}
{"nick":"antsmartian","reason":"Remote host closed the connection","date":"2018-10-20T07:44:00.126Z","type":"quit"}
{"nick":"addaleax","message":"btw, I appreciate any review I can get on https://github.com/nodejs/node/pull/23779 to un-break Travis CI :)","date":"2018-10-20T07:47:39.086Z","type":"message"}
{"nick":"antsmartian","date":"2018-10-20T07:54:26.593Z","type":"join"}
